---

- name: install apache
  apt: pkg=apache2
       state=latest

- name: enable modules
  command: a2enmod {{ item.module }}
           creates={{ item.creates }}
  with_items:
    - { module: rewrite, creates: /etc/apache2/mods-enabled/rewrite.load }
    - { module: vhost_alias, creates: /etc/apache2/mods-enabled/vhost_alias.load }
  notify:
    - restart apache

- name: mount nfs share
  mount: name=/var/www/{{ item.server_name }}
         src={{ item.nfs_mount }}
         fstype=nfs
         state=mounted
  with_items: apache.vhosts
  when: apache.nfs and apache.vhosts

- name: create vhost entry
  template: src=vhost.conf.j2
            dest=/etc/apache2/sites-available/{{ item.server_name }}.conf
            mode=0644
  with_items: apache.vhosts
  when: apache.vhosts

- name: link vhost entry
  file: src=/etc/apache2/sites-available/{{ item.server_name }}.conf
    dest=/etc/apache2/sites-enabled/{{ item.server_name }}.conf
    state=link
  with_items: apache.vhosts
  when: apache.vhosts
  notify:
      - restart apache
