---

- name: install apache
  apt: pkg={{ item}} state=latest
  with_items:
    - apache2
    - libapache2-mod-fastcgi

- name: set apache log folder permissions
  shell: chmod 0755 /var/log/apache2 &&
         find /var/log/apache2 -type f -exec chmod 0644 {} \; &&
         touch ~{{ ansible_ssh_user }}/.flag_set_apache_log_folder_permissions
         creates=~{{ ansible_ssh_user }}/.flag_set_apache_log_folder_permissions

- name: enable modules
  command: a2enmod {{ item }} creates=/etc/apache2/mods-enabled/{{ item }}.load
  with_items: apache.modules
  when: apache.modules
  notify:
    - restart apache

- name: create apache fqdn conf
  template: src=fqdn.j2 dest=/etc/apache2/conf-available/fqdn.conf mode=0644
  notify:
      - restart apache

- name: link apache fqdn conf
  file: src=/etc/apache2/conf-available/fqdn.conf dest=/etc/apache2/conf-enabled/fqdn.conf state=link
  notify:
    - restart apache

- name: create apache php5-fpm config
  copy: src=php5-fpm.conf dest=/etc/apache2/conf-available/php5-fpm.conf mode=0644
  notify:
    - restart apache

- name: enable apache configs
  command: a2enconf {{ item }} creates=/etc/apache2/conf-enabled/{{ item }}
  with_items:
    - fqdn.conf
    - php5-fpm.conf
  notify:
    - restart apache

- name: create vhost entries
  template: src=vhost.conf.j2 dest=/etc/apache2/sites-available/{{ item.server_name }}.conf mode=0644
  with_items: vhosts
  when: vhosts
  notify:
      - restart apache

- name: enable apache sites
  command: a2ensite {{ item.server_name }} creates=/etc/apache2/sites-enabled/{{ item.server_name }}
  with_items: vhosts
  notify:
    - restart apache
