---

- name: Install nfs-common
  apt: pkg=nfs-common state=latest

- name: mount nfs share
  mount: name={{ item.destination }}
         src={{ item.source }}
         fstype=nfs
         state=mounted
         opts=defaults,noatime,nodiratime,rsize=1048576,wsize=1048576,hard,intr
  with_items: nfs.mounts
  when: nfs.enabled and nfs.mounts
