---

- name: update apt cache if cache is older then 1 day
  apt: update_cache=yes cache_valid_time=86400

- name: install add-apt-repository command
  apt: pkg=python-software-properties state=latest

- name: add ppa:ondrej/php5
  command: add-apt-repository -y ppa:ondrej/php5 creates=/etc/apt/sources.list.d/ondrej-php5-precise.list
  notify:
    - update apt

- name: flush handlers
  meta: flush_handlers
