---

- name: update apt cache if cache is older than 1 day
  apt: update_cache=yes cache_valid_time=86400

- name: install packages required for vagrant
  apt: pkg={{ item }} state=latest
  with_items: apt.packages
  when: apt.packages
