---

-
    name: create files
    file: path={{ item.path }} src={{ item.src | default('') }} state={{ item.state | default('touch') }} mode={{ item.permissions }}
    with_items: files
    when: files
