---

- name: Install ntp
  apt: pkg=ntp
       state=latest

- name: Update timezone
  shell: echo {{ timezone }} > /etc/timezone && touch /home/vagrant/.flag_timezone
         creates=/home/vagrant/.flag_timezone
  notify:
    - update timezone
