---

- name: Install ntp
  apt: pkg=ntp state=latest

- name: Update timezone
  shell: echo {{ timezone }} > /etc/timezone && touch ~{{ ansible_ssh_user }}/.flag_timezone
         creates=~{{ ansible_ssh_user }}/.flag_timezone
  notify:
    - update timezone
