---

- name: Install ntp
  apt: pkg=ntp
       state=latest

- name: Update timezone
  shell: echo {{ timezone }} > /etc/timezone && touch /home/{{ ansible_user }}/.flag_timezone
         creates=/home/{{ ansible_user }}/.flag_timezone
  notify:
    - update timezone
