---

- name: restart ntp
  service: name=ntp state=restarted enabled=yes

- name: update timezone
  command: dpkg-reconfigure -f noninteractive tzdata
  notify:
    - restart ntp

- name: restart sshd
  service: name=ssh state=restarted enabled=yes
