---

- name: install mysql
  apt: pkg=mysql-server
       state=latest

- name: set mysql root password
  shell: mysqladmin -u root password {{ mysql.root_password }} >> /home/vagrant/.flag_mysql_root_password
         creates=/home/vagrant/.flag_mysql_root_password

- name: enable remote mysql login
  mysql_user: name=root
              password={{ mysql.root_password }}
              host=%
              priv=*.*:ALL,GRANT
              state=present
              login_user=root
              login_password={{ mysql.root_password }}

- name: update mysql config
  template: src=my.cnf.j2
            dest=/etc/mysql/my.cnf
            mode=0644
  notify:
    - restart mysql
