---

- name: install mysql server
  apt: pkg=mysql-server state=latest

- name: Copy the my.cnf file
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf mode=0644
  notify:
    - restart mysql

- name: enable remote mysql login
  mysql_user: name=root
              password={{ mysql.root_password }}
              host={{ item }}
              priv=*.*:ALL,GRANT
              state=present
  with_items: mysql.hosts
  notify:
    - restart mysql

- name: copy .my.cnf file with root password credentials
  template: src=.my.cnf.j2 dest=~/.my.cnf mode=0600

- name: ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items: mysql.hosts
  notify:
    - restart mysql

- name: remove the test database
  mysql_db: name=test state=absent
