---

- name: install mysql
  apt: pkg=mysql-server state=latest

- name: set mysql root password
  command: mysqladmin -u root password {{ mysql.root_password }} creates=/home/vagrant/.flag_mysql_root_password
  notify:
      - set mysql root password flag

- name: enable remote mysql login
  command: mysql --user=root --password={{ mysql.root_password }} -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '{{ mysql.root_password }}' WITH GRANT OPTION;" creates=/home/vagrant/.flag_mysql_remote_login
  notify:
        - set mysql remote login flag

- name: update mysql config
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf mode=0644
  notify:
    - restart mysql
