---

- name: install mysql server
  apt: pkg=mysql-server state=latest

- name: set mysql root password
  command: mysqladmin password {{ mysql.root_password }}
  notify:
    - restart mysql

- name: update mysql config
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf mode=0644
  notify:
    - restart mysql

- name: enable remote mysql login
  mysql_user: name=root
              password={{ mysql.root_password }}
              host=%
              priv=*.*:ALL,GRANT
              state=present
              login_user=root
              login_password={{ mysql.root_password }}
  notify:
    - restart mysql
