---

- name: install php
  apt: pkg=php5
       state=latest

- name: update php configs
  template: src=php.ini.j2
            dest={{ item }}
            mode=0644
  with_items:
    - /etc/php5/cli/php.ini
    - /etc/php5/apache2/php.ini
  notify:
    - restart apache
