---

- name: install php
  apt: pkg={{ item }} state=latest
  with_items:
    - php5
    - php5-cli
    - php5-fpm

- name: update php configs
  template: src=php.ini.j2 dest={{ item }} mode=0644
  with_items:
    - /etc/php5/cli/php.ini
    - /etc/php5/fpm/php.ini
  notify:
    - restart nginx
    - restart apache

- name: update php configs
  template: src=php.ini.j2 dest=/etc/php5/apache2/php.ini mode=0644
  when: apache.enabled
  notify:
    - restart apache
