---

- name: add dotdeb.org repo key
  apt_key: url=http://www.dotdeb.org/dotdeb.gpg state=present

- name: add dotdeb.org repo
  apt_repository: repo='{{ item }}' state=present
  with_items:
    - deb http://packages.dotdeb.org wheezy all
    - deb-src http://packages.dotdeb.org wheezy all
    - deb http://packages.dotdeb.org wheezy-php55 all
    - deb-src http://packages.dotdeb.org wheezy-php55 all

- name: install php
  apt: pkg=php5 state=latest

- name: update php configs
  template: src=php.ini.j2 dest={{ item }} mode=0644
  with_items:
    - /etc/php5/cli/php.ini
    - /etc/php5/apache2/php.ini
  notify:
    - restart apache
