---

- name: add ppa:ondrej/php5-5.6 repo
  command: add-apt-repository ppa:ondrej/php5-5.6 --yes

- name: install php
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - php5
    - php5-dev
    - php5-cli
    - php5-fpm

- name: update php configs
  template: src=php.ini.j2 dest={{ item }} mode=0644
  with_items:
    - /etc/php5/cli/php.ini
    - /etc/php5/fpm/php.ini
  notify:
    - restart nginx
    - restart apache
    - restart php5-fpm
