---

- name: install phalcon build tools
  apt: pkg={{ item }} state=latest
  with_items:
    - php5-dev
    - php5-mysql
    - gcc

- name: checkout phalcon
  command: git clone --depth=1 git://github.com/phalcon/cphalcon.git
           chdir=~{{ ansible_user }}
           creates=~{{ ansible_user }}/cphalcon

- name: check of phalcon is installed
  command: php --ri phalcon
  ignore_errors: true
  register: phalcon_check

- name: checkout phalcon tag
  shell: git fetch --all -t && git checkout -B {{ phalcon.version }} remotes/origin/{{ phalcon.version }}
         chdir=~{{ ansible_user }}/cphalcon
  when: phalcon.version not in phalcon_check.stdout

- name: install phalcon
  command: ./install chdir=~{{ ansible_user }}/cphalcon/build
  when: phalcon.version not in phalcon_check.stdout
  notify:
    - restart apache

- name: add phalcon configs
  copy: src=phalcon.ini dest={{ item }} mode=0644
  with_items:
    - /etc/php5/apache2/conf.d/20-phalcon.ini
    - /etc/php5/cli/conf.d/20-phalcon.ini
