---

- name: install nginx
  apt: pkg={{ item }} state=latest
  with_items:
    - nginx

- name: create vhost entries
  template: src=vhost.conf.j2 dest=/etc/nginx/sites-available/{{ item.server_name }}.conf mode=0644
  with_items: vhosts
  when: vhosts
  notify:
      - restart nginx

- name: link vhost entries
  file: src=/etc/nginx/sites-available/{{ item.server_name }}.conf
        dest=/etc/nginx/sites-enabled/{{ item.server_name }}.conf
        state=link
  with_items: vhosts
  when: vhosts
  notify:
    - restart nginx
