---

- hosts: web_servers
  roles:
    - nfs
    - php
    - {role: hhvm, when: hhvm.enabled}
    - {role: memcached, when: memcached.enabled}
    - {role: nginx, when: nginx.enabled}
    - {role: apache, when: apache.enabled}
    - {role: nodejs, when: nodejs.enabled}
